WITH SENDERS (
    USER_ID,
    SENDED_AMOUNT
) AS (
    SELECT
        SENDER,
        SUM(AMOUNT) 
    FROM
        TRANSACTIONS_02
    GROUP BY 
        SENDER
), RECEIVERS (
    USER_ID,
    RECEIVED_AMOUNT
) AS (
    SELECT
        RECEIVER,
        SUM(AMOUNT)
    FROM
        TRANSACTIONS_02
    GROUP BY
        RECEIVER
)
SELECT
    COALESCE(SENDERS.USER_ID, RECEIVERS.USER_ID) AS USER_ID,
    COALESCE(RECEIVERS.RECEIVED_AMOUNT, 0) - COALESCE(SENDERS.SENDED_AMOUNT, 0) AS NET_CHANGES
FROM
    SENDERS
    RIGHT JOIN RECEIVERS ON SENDERS.USER_ID = RECEIVERS.USER_ID
UNION
SELECT
    COALESCE(SENDERS.USER_ID, RECEIVERS.USER_ID) AS USER_ID,
    COALESCE(RECEIVERS.RECEIVED_AMOUNT, 0) - COALESCE(SENDERS.SENDED_AMOUNT, 0) AS NET_CHANGES
FROM
    SENDERS
    LEFT JOIN RECEIVERS ON SENDERS.USER_ID = RECEIVERS.USER_ID
