WITH POSITIONS AS (
    SELECT
        ID AS USER_ID,
        ACTION_DATE AS DATES,
        ROW_NUMBER() OVER(
            PARTITION BY
                ID
            ORDER BY ACTION_DATE DESC
        ) AS POSITION
    FROM
        DATES_04
), LAST AS (
    SELECT
        POSITIONS.USER_ID,
        POSITIONS.DATES
    FROM
        POSITIONS
    WHERE
        POSITIONS.POSITION = 1
), SECOND_LAST AS (
    SELECT
        POSITIONS.USER_ID,
        POSITIONS.DATES
    FROM
        POSITIONS
    WHERE
        POSITIONS.POSITION = 2
)
SELECT
    LAST.USER_ID,
    DATEDIFF(LAST.DATES, SECOND_LAST.DATES) AS DAYS_ELAPSED
FROM
    LAST
    LEFT JOIN SECOND_LAST ON LAST.USER_ID = SECOND_LAST.USER_ID
