WITH USERS AS (
    SELECT DISTINCT 
        USER_ID
    FROM
        TRANSACTIONS_05
), TRANSACTIONS AS (
    SELECT 
        USER_ID,
        TRANSACTION_DATE AS DATES,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID
            ORDER BY TRANSACTION_DATE
        ) AS POSITION
    FROM
        TRANSACTIONS_05
), SUPERS AS (
    SELECT 
        TRANSACTIONS.USER_ID,
        TRANSACTIONS.DATES AS DATE_AS_SUPER
    FROM
        TRANSACTIONS 
    WHERE 
        TRANSACTIONS.POSITION = 2
)
SELECT 
    USERS.USER_ID,
    SUPERS.DATE_AS_SUPER
FROM
    USERS
    LEFT JOIN SUPERS ON USERS.USER_ID = SUPERS.USER_ID
