WITH USERS (
    USER_ID
) AS (
    SELECT DISTINCT 
        USER_ID
    FROM
        USERS_05
), TRANSACTIONS (
    USER_ID,
    DATES,
    POSITION 
) AS (
    SELECT 
        USER_ID,
        TRANSACTION_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID
            ORDER BY TRANSACTION_DATE
        )
    FROM
        USERS_05
), SUPERS (
    USER_ID,
    DATE_AS_SUPER
) AS (
    SELECT 
        TRANSACTIONS.USER_ID,
        TRANSACTIONS.DATES
    FROM
        TRANSACTIONS 
    WHERE 
        TRANSACTIONS.POSITION = 2
)
SELECT 
    USERS.USER_ID,
    SUPERS.DATE_AS_SUPER
FROM
    USERS
    LEFT JOIN SUPERS ON USERS.USER_ID = SUPERS.USER_ID
